### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by METAcgg** [mikenye/docker-split2flac#1]
I am very interested in using the container but i am a bit lost...
I am a newbie and i discovered docker just a few weeks ago and my linux knowledge is very limited. My goal is to split flac files when deluge finishes a download. 
I already have the binhex /arch-delugevpn working. I would like to use the execute plug-in within deluge to lunch split2flac in a specific directory.
I have installed a split2flac container but it trashes when i launch it. I thought i have to start it within the delugevpn container. I have unsuccessfully tried to use the "alias split2flac='docker run -v "$(pwd)":/workdir -it --rm mikenye/split2flac'" in the terminal of delugevpn.

Thank you for your help

**Comment by mikenye** [comment]
Hi @METAcgg, apologies for the delayed response - day job has been very busy.

If I'm understanding your issue correctly, you wish to run the split2flac container inside another container?

If so, I'm not sure this is the right way to achieve your goal.

Ideally deluge would output files somewhere that can be access by the host, and then you would run the split2flac container against those files.

I can try to walk you through this process.

Firstly, I'll need some information from your deluge container. Can you please do the following:

1. Type `docker ps` and find the name of your deluge container.
2. Type `docker inspect <name>`, replacing `<name>` with the name of your deluge container.

**Go through the output of the above commands and redact any confidential information!**

Eg, I can see from the `binhex/arch-delugevpn` readme that there are several environment variables that may contain sensitive information that you should redact, eg: `VPN_USER`, `VPN_PASS`. Don't post these on a public forum.

Once I have the above output, I'll know how you have the deluge container configured and I'll be able to better help you.

Is your end goal to use the execute plugin of deluge to automatically run split2flac?

Thanks, I look forward to helping you.

**Comment by METAcgg** [comment]
Thanks!
I kept looking and i think the first issue is to give access to my deluge container to docker. I am running everything on a Synology NAS and it seems a bit tricky to mount /var/run/docker.sock with synology system.
I've managed to mount it but still don't have access to docker.
Here is the result of the docker inspect :

```
[
    {
        "Id": "4c8d2128102e78bc365bfaa78f512b738d44cb2a3bf040b3584b7049cdc35834",
        "Created": "2020-04-23T19:50:32.818266383Z",
        "Path": "/usr/bin/tini",
        "Args": [
            "--",
            "/bin/bash",
            "/usr/local/bin/init.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 30687,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-04-23T19:50:37.674762245Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "StartedTs": 1587671437,
            "FinishedTs": -62135596800
        },
        "Image": "sha256:7975a483b340e8e883323799192f3f792d98b4f728ddd4a32d1f5e24d61ee943",
        "ResolvConfPath": "/volume1/@docker/containers/4c8d2128102e78bc365bfaa78f512b738d44cb2a3bf040b3584b7049cdc35834/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/4c8d2128102e78bc365bfaa78f512b738d44cb2a3bf040b3584b7049cdc35834/hostname",
        "HostsPath": "/volume1/@docker/containers/4c8d2128102e78bc365bfaa78f512b738d44cb2a3bf040b3584b7049cdc35834/hosts",
        "LogPath": "/volume1/@docker/containers/4c8d2128102e78bc365bfaa78f512b738d44cb2a3bf040b3584b7049cdc35834/log.db",
        "Name": "/deluge_vpn",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": [
            "7e06c5517dd8b30d53e82b1f4fa0d00b38cd9a0fbbf4162cdcc872fc0ece5910"
        ],
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/var/run/docker.sock:/var/run/docker.sock",
                "/volume1/Downloads/Deluge:/data",
                "/volume1/docker/delugevpn2/config:/config"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "58846/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "58846"
                    }
                ],
                "58946/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "58946"
                    }
                ],
                "58946/udp": [
                    {
                        "HostIp": "",
                        "HostPort": "58946"
                    }
                ],
                "8112/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8112"
                    }
                ],
                "8118/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8118"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/home/nobody",
                "TERM=xterm",
                "LANG=en_GB.UTF-8",
                "DELUGE_DAEMON_LOG_LEVEL=info",
                "TZ=Europe/Paris",
                "VPN_USER=********",
                "LAN_NETWORK=192.168.2.0/24",
                "PUID=1024",
                "VPN_PASS=*******",
                "VPN_ENABLED=yes",
                "VPN_PROV=S********",
                "UMASK=000",
                "OPENVPN_OPTS=-inactive 3600 -ping 10 -ping-exit 60",
                "ENABLE_PRIVOXY=yes",
                "NAME_SERVERS=8.8.8.8,8.8.4.4,80.10.246.2,80.10.246.129",
                "DELUGE_WEB_LOG_LEVEL=info",
                "DEBUG=false",
                "PGID=100",
                "STRICT_PORT_FORWARD=yes"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/Downloads/Deluge",
                "Destination": "/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/docker/delugevpn2/config",
                "Destination": "/config",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "4c8d2128102e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "58846/tcp": {},
                "58946/tcp": {},
                "58946/udp": {},
                "8112/tcp": {},
                "8118/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/home/nobody",
                "TERM=xterm",
                "LANG=en_GB.UTF-8",
                "DELUGE_DAEMON_LOG_LEVEL=info",
                "TZ=Europe/Paris",
                "VPN_USER=**********",
                "LAN_NETWORK=192.168.2.0/24",
                "PUID=1024",
                "VPN_PASS=********",
                "VPN_ENABLED=yes",
                "VPN_PROV=S",
                "UMASK=000",
                "OPENVPN_OPTS=-inactive 3600 -ping 10 -ping-exit 60",
                "ENABLE_PRIVOXY=yes",
                "NAME_SERVERS=8.8.8.8,8.8.4.4,80.10.246.2,80.10.246.129",
                "DELUGE_WEB_LOG_LEVEL=info",
                "DEBUG=false",
                "PGID=100",
                "STRICT_PORT_FORWARD=yes"
            ],
            "Cmd": [
                "/bin/bash",
                "/usr/local/bin/init.sh"
            ],
            "ArgsEscaped": true,
            "Image": "binhex/arch-delugevpn",
            "Volumes": {
                "/config": {},
                "/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/tini",
                "--"
            ],
            "OnBuild": null,
            "Labels": {},
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "0d94f0a3dfb869fdd5e48bb6240820088d393114748c94477858c40767e2760d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "58846/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "58846"
                    }
                ],
                "58946/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "58946"
                    }
                ],
                "58946/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "58946"
                    }
                ],
                "8112/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8112"
                    }
                ],
                "8118/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8118"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/0d94f0a3dfb8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "a60698408f91c76cc67e5cac305ce877f8e61b79204b45bee862d9b28e7b35ce",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.11",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:0b",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d400dd4f9e5bb65f9642d12df9e08511482f29d736672f04c676834b1413bf7c",
                    "EndpointID": "a60698408f91c76cc67e5cac305ce877f8e61b79204b45bee862d9b28e7b35ce",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.11",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:0b",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

My end goal is exactly to lunch split2flac when my deluge container finishes a download in order to lidarr to import correctly my files.

**Comment by mikenye** [comment]
So now that you have the docker socket mounted into your container, can you get a shell onto your container and run the command `docker run --rm hello-world`? You should get output like this:

```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:8e3114318a995a1ee497790535e7b88365222a21771ae7e53687ad76563e8e76
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by METAcgg** [comment]
unfortunately, it is not working. I have
bash: docker: command not found 
Any idea?

**Comment by mikenye** [comment]
That just means docker isn't installed.

We could install it into the container, however the problem is that containers are designed to be destroyed and recreated and not hold anything "permanent". If we start modifying your deluge container, you run the risk of losing your changes when you recreate the container.

You could consider creating your own custom container including split2flac and deluge eventually.

For now, I'll help you along the way as a learning exercise but please be aware this probably isn't the right way to go about what you want to achieve. :-)

The `binhex/arch-deluge` image uses Arch Linux, which uses `pacman` for package management. So, to install docker, type:

```
pacman -S docker
```

You should be prompted for confirmation, then it will download packages and install.

At this point, if you have `/var/run/docker.sock` mounted from your Synology, you should be able to re-try your `docker run --rm hello-world` command.

Let me know how you fare.

**Comment by METAcgg** [comment]
I don't really understand. Obviously docker is installed on my synology. Why sould i installed docker inside a container. I've read a tutorial on portainer for synology and the issue is the same. It seemed that just mounting docker.sock will solve everything but it is not in my case. Is there a docker instance inside the portainer container ?
Here is the [link](https://community.synology.com/enu/forum/1/post/125018)
I don't really like the idea of modifying a container. 
Maybe there is another way around to communicate fromm deluge container to your container ?

**Comment by mikenye** [comment]
You need the docker command line tool within the container in order to interact with the docker service on your Synology. The Portainer container works this way too.

**Comment by mikenye** [comment]
You could take a look at [mikenye/striparr](https://hub.docker.com/r/mikenye/striparr). It might be similar to adap the container to do something similar for split2flac...

**Comment by METAcgg** [comment]
Is there another way to achieve my goal ? I am afraid that if i modify the delugevpn container, every time i update it i have to redo everything. What do you think ?

**Comment by METAcgg** [comment]
It is indeed similar but the problem is that lidarr launches downloads and is not able to import because it doesn't handle cue files. To me it is really a missing feature that headphones seems to have. Several people report this lack but the people behind lidarr do not seem to care too much..
Can we make lidarr launch split2flac before importing a folder ?

**Comment by mikenye** [comment]
I've been meaning to deploy lidarr so I'll do that and have a look.

In the meantime, we can build an image based on the `binhex/arch-deluge` image that includes `split2flac`.

Create an empty folder, create a new file in the folder called `Dockerfile` and place the code below into it.

```dockerfile
FROM binhex/arch-deluge

RUN set -x && \
    pacman -Sy --noconfirm \
        enca \
        faac \
        flac \
        git \
        id3lib \
        imagemagick \
        lame \
        libmp4v2 \
        mac \
        vorbis-tools \
        wavpack \
        && \
    git clone https://github.com/ftrvxmtrx/split2flac.git /opt/split2flac && \
    ln -s /opt/split2flac/split2flac /usr/local/bin/split2flac
```

You can then run the command `docker build -t metacgg/arch-deluge-split2flac .` in the container to build your image.

Alternatively, Portainer has "build a new image" where you could do this.

**Comment by METAcgg** [comment]
I am sorry but i dont know where to find Dockerfile folder.

**Comment by mikenye** [comment]
Just make any empty folder somewhere, change to that directory, create a file named `Dockerfile`, put the code above into the file, and run the docker build command.

**Comment by mikenye** [comment]
This might help: https://docs.docker.com/get-started/part2/

**Comment by METAcgg** [comment]
I now have a custom image. I guess i do something like that:
`docker run -d --name=deluge_vpn_split --privileged --restart=always -v /etc/localtime:/etc/localtime:ro -v /volume1/Downloads/Deluge:/data -v /volume1/docker/delugevpn2/config:/config -p 8112:8112 -p 8118:8118 -p 58846:58846 -p 58946:58946 -p 58946:58946/udp -e VPN_ENABLED=yes -e VPN_PROV=*** -e ENABLE_PRIVOXY=yes -e LAN_NETWORK=192.168.2.0/24 -e NAME_SERVERS=8.8.8.8,8.8.4.4,80.10.246.2,80.10.246.129 -e DELUGE_DAEMON_LOG_LEVEL=info -e DELUGE_WEB_LOG_LEVEL=info -e DEBUG=false -e UMASK=000 -e PUID=*** -e PGID=*** -e TZ=Europe/Paris -e STRICT_PORT_FORWARD=yes -e VPN_USER=*** -e VPN_PASS=**** -e OPENVPN_OPTS="-inactive 3600 -ping 10 -ping-exit 60" metacgg/arch-delugevpn-split2flac`

**Comment by mikenye** [comment]
Yep! And split2flac is installed in the container too.

**Comment by METAcgg** [comment]
It seems to work! 
I now have to figure out how to use split2flac with deluge-execute. I might need your help again.
Another query, how should i proceed to update the metacgg container ?

**Comment by METAcgg** [comment]
I have manually tried on several folder and i have always the same error 
`Failed to get number of tracks from CUE sheet.                                                                                                                                                              
There may be an error in the sheet.                                                                                                                                                                         
/usr/local/bin/split2flac: line 125: printf: `N': invalid format character                                                                                                                                  
Running cueprint -n 1 -i cue -t /usr/local/bin/split2flac: line 452: cueprint: command not found `
I understand that my cue file might be not perfect but i have tried on 10 different and it is always the same.
Any clue?
Thank you very much for your help.

**Comment by mikenye** [comment]
It looks like a dependency for split2flac is missing. I’ll look into this and report back soon.

**Comment by METAcgg** [comment]
Thank you very much for your help!

**Comment by mikenye** [comment]
OK, so `cueprint` is included in the package `cuetools`, so this will need to be added to the `Dockerfile`.

Try this:

```dockerfile
FROM binhex/arch-deluge

RUN set -x && \
    pacman -Sy --noconfirm \
        cuetools \
        enca \
        faac \
        flac \
        git \
        id3lib \
        imagemagick \
        lame \
        libmp4v2 \
        mac \
        vorbis-tools \
        wavpack \
        && \
    git clone https://github.com/ftrvxmtrx/split2flac.git /opt/split2flac && \
    ln -s /opt/split2flac/split2flac /usr/local/bin/split2flac
```

**Comment by METAcgg** [comment]
It is totally working! I had to also add shntool. I have managed to configure deluge execute to do exactly what i wanted. Thank you very much for your help and your time!

**Comment by mikenye** [comment]
That's great to hear. Well done on getting it all working.
