### ISSUE TITLE
Change output files owner and/or permissions

### ISSUE THREAD

**Issue by shperrung** [mikenye/docker-split2flac#2]
Hi!
Your script is awesome! Thank a lot for this magic tool.
Output flac's has 755 root:root permissions. How to set it as 777 or run script as unpriveleged user?

**Comment by mikenye** [comment]
@shperrung thanks for the kind words.

You can change the user the container runs as by passing the `--user` argument to your `docker run` command. 

Have a look at the documentation here: https://docs.docker.com/engine/reference/run/#user

**Comment by shperrung** [comment]
Hi!
Sorry for noob questions but still can't get output files with "non-root" ownership. I set --user=1000:1001 but it doesn't work because of insufficient rights.
`dude@server:/mnt/pool/media/music/Megadeth - Discography (lossless)/Albums/1990 - Rust In Peace/2013 Toshiba, TOCP-95119, SHM-CD, Japan, Remastered$ docker run --user=1000:1001 -v "$(pwd)":/workdir -it --rm mikenye/split2flac -cue './Megadeth - Rust In Peace [Toshiba, TOCP-95119, SHM-CD, Japan].cue' './Megadeth - Rust In Peace [Toshiba, TOCP-95119, SHM-CD, Japan].flac'                                       Output format : FLAC [using flake tool] (-8)                                       Output dir    : .                                                                  mktemp: failed to create file via template '//.split2flac_XXXXX.cue': Permission denied                                                                               /split2flac/split2flac: 382: /split2flac/split2flac: cannot create : Directory nonexistent                                                                            Unable to save converted cue sheet                                                 Finished                            `
Another kind  **--user=dude:band** says me that _docker: Error response from daemon: unable to find user dude: no matching entries in passwd file._

**Comment by mikenye** [comment]
Sorry @shperrung, I gave you bad advice earlier.

Try this:

```
docker run -v "$(pwd)":/workdir -e PUID=$(id -u) -e PGID=$(id -g) -it --rm mikenye/split2flac <remainder_of_commandline>
```

**Comment by mikenye** [comment]
I should mention that before the above command will work, you'll have to pull the latest version of the image: `docker pull mikenye/split2flac`.

**Comment by shperrung** [comment]
Hi, mikenye!
Looks like it didn't become better. I can't convert anything using new command and prevous also doesn't work:
```
dude@server:/mnt/pool/media/music/Megadeth - Discography (lossless)/Aldocker run -v "$(pwd)":/workdir -e PUID=$(id -u) -e PGID=$(id -g) -it --rm mikenye/split2flac -cue './Megadeth - Countdown To Extinction [Toshiba, TOCP-95120, SHM-CD, Japan].cue' './Megadeth - Countdown To Extinction [Toshiba, TOCP-95120, SHM-CD, Japan].flac'
Output format : FLAC [using flake tool] (-8)
Output dir    : .
mktemp: failed to create file via template '/root/.split2flac.cue.XXXXXX': Permission denied
/split2flac/split2flac: 382: /split2flac/split2flac: cannot create : Directory nonexistent
Unable to save converted cue sheet

Finished
```
Starting by sudo or root doesn't help.
Can you return back "previous" version of this amazing container? I'll try to solve my request by post command:
`sudo docker run -v "$(pwd)":/workdir -it --rm mikenye/split2flac -cue './Megadeth.cue' './Megadeth.flac' && chown -R dude:band ./`

**Comment by mikenye** [comment]
Hi @shperrung, I can fix the error, please bear with me as I'd like to fix these permissions issues instead of revert to the old (broken) way of having to `chown` everything after conversion.

Please `docker pull mikenye/split2flac:latest` and retry the command:

```shell
docker run -v "$(pwd)":/workdir -e PUID=$(id -u) -e PGID=$(id -g) -it --rm mikenye/split2flac -cue './Megadeth - Countdown To Extinction [Toshiba, TOCP-95120, SHM-CD, Japan].cue' './Megadeth - Countdown To Extinction [Toshiba, TOCP-95120, SHM-CD, Japan].flac'
```

Thanks!

**Comment by shperrung** [comment]
Excellent update! The script in container works as expected. Output files pick up current user:group.
Thank you 😊!

**Comment by mikenye** [comment]
Awesome, thanks for letting me know!
